### PR TITLE
feat: ✨ update supervision to 0.18.0

### PR DESCRIPTION
**Pull request by onuralpszr**
Hello @giswqs;

feat: ✨ add 2 new maintainers
fix: drop python 3.7
fix: add dependencies(scipy,defusedxml,tqdm,requests) to recipe

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by onuralpszr** [comment]
@giswqs azure devops is passed and built, If you ready let's merge and test it.

**Comment by giswqs** [comment]
Merged! Thank you for your contribution

**Comment by onuralpszr** [comment]
> Merged! Thank you for your contribution 

Thank you for the quick merge, too.  😀

**Pull request merged**
